# Generated by Django 4.2 on 2023-05-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("name", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="technologies",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="about", name="career", field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name="about", name="heading", field=models.CharField(max_length=225),
        ),
    ]
