# Generated by Django 4.2 on 2023-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("name", "0002_portfolio_description_portfolio_technologies_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="portfolio", name="video_url",),
        migrations.AddField(
            model_name="portfolio",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="portfolio/videos/"
            ),
        ),
    ]
